bind 127.0.0.1
port 6379
daemonize no
loglevel notice
logfile ""
databases 16

save ""
stop-writes-on-bgsave-error no

maxmemory 2gb
maxmemory-policy allkeys-lfu
maxmemory-samples 10

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes

appendonly no
activerehashing yes